# Generated by Django 5.2.7 on 2025-10-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downloaded_gb',
            field=models.FloatField(default=0.0),
        ),
    ]
