# Generated by Django 5.2.6 on 2025-09-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('removal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimerSession',
        ),
    ]
