# Generated by Django 5.2.6 on 2025-09-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('removal', '0002_delete_timersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(verbose_name='client id')),
                ('task_name', models.CharField(default='Removal', max_length=100, verbose_name='task_name')),
                ('current_time', models.DurationField(verbose_name='current_time')),
                ('target_time', models.DurationField(verbose_name='goal-time')),
                ('completion_percentage', models.IntegerField(default=0, verbose_name='percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Removal Task',
                'verbose_name_plural': 'Removal Tasks',
            },
        ),
    ]
