# Generated by Django 5.2.6 on 2025-09-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('removal', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemovalTask',
        ),
    ]
