# Generated by Django 5.2.6 on 2025-09-09 06:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('removal', '0004_delete_removaltask'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ক্লায়েন্ট আইডি')),
                ('task_name', models.CharField(default='Removal', max_length=100, verbose_name='কাজের নাম')),
                ('current_time', models.DurationField(verbose_name='বর্তমান সময়')),
                ('target_time', models.DurationField(verbose_name='লক্ষ্য সময়')),
                ('completion_percentage', models.IntegerField(default=0, verbose_name='সম্পন্ন শতাংশ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Removal Task',
                'verbose_name_plural': 'Removal Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_images/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='removal.removaltask')),
            ],
        ),
    ]
