# Generated by Django 5.2.6 on 2025-09-09 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removaltask',
            name='client_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Client_id'),
        ),
        migrations.AlterField(
            model_name='removaltask',
            name='completion_percentage',
            field=models.IntegerField(default=0, verbose_name='percentage'),
        ),
        migrations.AlterField(
            model_name='removaltask',
            name='current_time',
            field=models.DurationField(verbose_name='current time'),
        ),
        migrations.AlterField(
            model_name='removaltask',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='add note'),
        ),
        migrations.AlterField(
            model_name='removaltask',
            name='target_time',
            field=models.DurationField(verbose_name='goal-time'),
        ),
        migrations.AlterField(
            model_name='removaltask',
            name='task_name',
            field=models.CharField(default='Removal', max_length=100, verbose_name='taskname'),
        ),
    ]
