# Generated by Django 5.2.6 on 2025-09-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('removal', '0006_alter_removaltask_client_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskimage',
            name='task',
        ),
        migrations.DeleteModel(
            name='RemovalTask',
        ),
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
