# Generated by Django 5.2.6 on 2025-09-11 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('removal', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskimage',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
