# Generated by Django 5.2.6 on 2025-09-15 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('removal', '0011_taskboiler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskBoiler',
        ),
    ]
