# Generated by Django 5.2.6 on 2025-09-15 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal', '0012_delete_taskboiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBoiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('current_time', models.DurationField()),
                ('target_time', models.DurationField()),
                ('completion_percentage', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iconName', models.CharField(blank=True, max_length=50, null=True)),
                ('iconColor', models.CharField(blank=True, max_length=7, null=True)),
                ('iconType', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskds', to='removal.client')),
            ],
        ),
    ]
