# Generated by Django 5.2.6 on 2025-09-15 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal', '0013_taskboiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskboiler',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskds', to='removal.client'),
        ),
    ]
