# Generated by Django 5.2.6 on 2025-09-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('removal', '0014_alter_taskboiler_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskboiler',
            name='completion_percentage',
        ),
    ]
