# Generated by Django 5.2.7 on 2025-10-13 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal', '0016_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskboiler',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskds', to='removal.client'),
        ),
    ]
